openapi: 3.0.3
info:
  title: 공예쁨 Swagger
  description: |-
    공예쁨 서비스를 위한 개발 서버 전용 API SPEC 입니다.
  version: 1.0.11
servers:
  - url: https://dev.leporem.art
components:
  securitySchemes:
    leporemartTokenAuth:
      type: http
      scheme: bearer
security:
  - leporemartTokenAuth: []
tags:
  - name: users
    description: 사용자 관리
  - name: buyers
    description: 구매자 관리
  - name: sellers
    description: 판매자 관리
  - name: items
    description: 작품 관리
  - name: notifications
    description: 알림 관리

paths:
  /users/signup/kakao:
    post:
      tags:
        - users
      summary: 카카오 회원가입
      description: 카카오로 회원가입합니다.
      requestBody:
        description: ID 토큰을 통하여 카카오 회원가입을 처리합니다.
        content:
          application/json:
            schema:
              type: object
              properties:
                id_token:
                  type: string
                  example: Leporemart33!
                is_argree_privacy:
                  type: boolean
                  example: true
                is_agree_terms:
                  type: boolean
                  example: true
                is_agree_ads:
                  type: boolean
                  example: true
                nickname:
                  type: string
                  example: 공예쁨
        required: true
      responses:
        '201':
          description: 회원가입 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      access_token:
                        type: string
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm92aWRlciI6IktBS0FPIiwiZW1haWwiOiIyOTE5MzQ2MzEwIiwiZXhwIjoxNjkyMTE2MDU1LCJpYXQiOjE2OTIxMDUyNTV9.gjxXxYzfNzVHCRNSQgKDO2QRdjzPi_WnMKEbRX8G7mg
                      refresh_token:
                        type: string
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm92aWRlciI6IktBS0FPIiwiZW1haWwiOiIyOTE5MzQ2MzEwIiwiZXhwIjoxNzA3NjU3MjU1LCJpYXQiOjE2OTIxMDUyNTV9.ZjwtgdnADBuw-Hkv5rxRXnv8br5s0UWz3ym0FhvbHG4
                      access_exp: 
                        type: integer
                        example: 1692116055
        '400':
          description: 회원가입 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 실패 원인
                    example: duplicate nickname
  
  /users/login/kakao:
    post:
      tags:
        - users
      summary: 카카오 로그인 API
      description: 카카오 로그인 url 입니다.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id_token:
                  type: string
                  example: eyJraWQiOiI5ZjI1MmRhZGQ1ZjIzM2Y5M2QyZmE1MjhkMTJmZWEiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI4YWVhYzliYjE4ZjQyMDYwYTIzMzI4ODU1NzdiOGNiOSIsInN1YiI6IjI5MTkzNDYzMTAiLCJhdXRoX3RpbWUiOjE2OTIxMDQyOTEsImlzcyI6Imh0dHBzOi8va2F1dGgua2FrYW8uY29tIiwiZXhwIjoxNjkyMTQ3NDkxLCJpYXQiOjE2OTIxMDQyOTF9.aC8-RvYFfoNLf8ZrL1MjwQoQWQ8CGVnc4SwDWFTsUfqwso08XwKdbR6YueK0d3uZShc50XSo94afruuV622MSvvtrYXFG4MtGTYu3BrmxeTnHyzTMVVEdYb5mpgOodbALWQH_BFepfZ-c8bry5hMELZSpDxDy-DidfhCuFDTOc1bq1phXwCk4b6vMXf9Ggfa8dAXzlEmMSVrAvsOc_4N4QF14NOnFVLJMVvzx6J9Upih7MowaAIx74zSeATbOifkGx9NwGDqVekC3GzVcddQdwNEgFDP_X0rKa4m9v8Y8JpLezB17TENzHjBsPtmCewvZp2HODMtDXF4-jW_v3Q3tA
        required: true          
      responses:
        '200':
          description: 카카오 로그인 성공, 공예쁨에 존재하는 사용자
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                    example: 1
                  is_seller:
                    type: boolean
                    example: true
                  nickname:
                    type: string
                    example: 공예쁨
                  access_token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm92aWRlciI6IktBS0FPIiwiZW1haWwiOiIyOTE5MzQ2MzEwIiwiZXhwIjoxNjkyMTE2MDU1LCJpYXQiOjE2OTIxMDUyNTV9.gjxXxYzfNzVHCRNSQgKDO2QRdjzPi_WnMKEbRX8G7mg
                  refresh_token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm92aWRlciI6IktBS0FPIiwiZW1haWwiOiIyOTE5MzQ2MzEwIiwiZXhwIjoxNzA3NjU3MjU1LCJpYXQiOjE2OTIxMDUyNTV9.ZjwtgdnADBuw-Hkv5rxRXnv8br5s0UWz3ym0FhvbHG4
                  access_exp:
                    type: integer
                    example: 1692116055
        '403':
          description: 카카오 로그인 성공, 공예쁨에 존재하지 않는 사용자
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: signin failed


  /users/redirect/apple:
    get:
      tags: 
        - users
      summary: 애플 로그인 Redirect URI
      description: 애플 로그인 리다이렉트 uri 입니다.
      responses:
        '200':
          description: 애플 로그인 성공, 공예쁨에 존재하는 사용자
          content:
            application/json:
              example:
                message: success
                data:
                  user_id: 4
                  is_seller: false
                  nickname: 옥지얌
                  access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm92aWRlciI6IkFQUExFIiwiZW1haWwiOiIwMDAzMTkuYWIwYjk0NTNhMWE5NDgxNzhiOGQ4MWE5NzRjN2YwMTUuMTcyMiIsImV4cCI6MTY5MjAzOTA4NCwiaWF0IjoxNjkyMDI4Mjg0fQ.-Y5RtpVnB1zXQksA9fNKXYCB3D_qMfInXMTYbLp8NNE
                  refresh_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm92aWRlciI6IkFQUExFIiwiZW1haWwiOiIwMDAzMTkuYWIwYjk0NTNhMWE5NDgxNzhiOGQ4MWE5NzRjN2YwMTUuMTcyMiIsImV4cCI6MTcwNzU4MDI4NCwiaWF0IjoxNjkyMDI4Mjg0fQ.XWeYAH80bEMfwQCG9bQTrd-46zP5bACEKSw9cSBLRiU
                  access_exp: 1692039084
        '404':
          description: 애플 로그인 성공, 공예쁨에 존재하지 않는 사용자
          content:
            application/json:
              example:
                message: signup required
                user_data: 000319.ab0b9453a1a948178b8d81a974c7f015.1722
  
  /users/login/apple:
    get:
      tags: 
        - users
      summary: 애플 로그인
      description: 애플 로그인입니다.
      parameters:
        - in: query
          name: code
          schema:
            type: string
          required: true
      responses:
        '200':
          description: 애플 로그인 성공, 공예쁨에 존재하는 사용자
          content:
            application/json:
              example:
                message: success
                data:
                  user_id: 4
                  is_seller: false
                  nickname: 옥지얌
                  access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm92aWRlciI6IkFQUExFIiwiZW1haWwiOiIwMDAzMTkuYWIwYjk0NTNhMWE5NDgxNzhiOGQ4MWE5NzRjN2YwMTUuMTcyMiIsImV4cCI6MTY5MjAzOTA4NCwiaWF0IjoxNjkyMDI4Mjg0fQ.-Y5RtpVnB1zXQksA9fNKXYCB3D_qMfInXMTYbLp8NNE
                  refresh_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm92aWRlciI6IkFQUExFIiwiZW1haWwiOiIwMDAzMTkuYWIwYjk0NTNhMWE5NDgxNzhiOGQ4MWE5NzRjN2YwMTUuMTcyMiIsImV4cCI6MTcwNzU4MDI4NCwiaWF0IjoxNjkyMDI4Mjg0fQ.XWeYAH80bEMfwQCG9bQTrd-46zP5bACEKSw9cSBLRiU
                  access_exp: 1692039084
        '404':
          description: 애플 로그인 성공, 공예쁨에 존재하지 않는 사용자
          content:
            application/json:
              example:
                message: signup required
                user_data: 000319.ab0b9453a1a948178b8d81a974c7f015.1722

  /users/signup/apple:
    post:
      tags:
        - users
      summary: 애플 회원가입
      description: 애플 로그인 유저 회원가입입니다.
      requestBody:
        content:
          application/json:
            schema:
              properties:
                user_data: 
                  type: string
                  example: 000319.ab0b9453a1a948178b8d81a974c7f015.1722
                is_argree_privacy:
                  type: boolean
                  example: true
                is_agree_terms:
                  type: boolean
                  example: true
                is_agree_ads:
                  type: boolean
                  example: false
                nickname:
                  type: string
                  example: 옥지얌
        required: true
      responses:
        '201':
          description: 회원가입 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: signup successful
                  data:
                    type: object
                    properties:
                      access_token:
                        type: string
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm92aWRlciI6IkFQUExFIiwiZW1haWwiOiIwMDAzMTkuYWIwYjk0NTNhMWE5NDgxNzhiOGQ4MWE5NzRjN2YwMTUuMTcyMiIsImV4cCI6MTY5MjAzOTA4NCwiaWF0IjoxNjkyMDI4Mjg0fQ.-Y5RtpVnB1zXQksA9fNKXYCB3D_qMfInXMTYbLp8NNE
                      refresh_token:
                        type: string
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm92aWRlciI6IkFQUExFIiwiZW1haWwiOiIwMDAzMTkuYWIwYjk0NTNhMWE5NDgxNzhiOGQ4MWE5NzRjN2YwMTUuMTcyMiIsImV4cCI6MTcwNzU4MDI4NCwiaWF0IjoxNjkyMDI4Mjg0fQ.XWeYAH80bEMfwQCG9bQTrd-46zP5bACEKSw9cSBLRiU
                      access_exp:
                        type: integer
                        example: 1692039084
        '400':
          description: 회원가입 실패
          content:
            application/json:
              examples:
                duplicate nickname:
                  value:
                    message: 중복된 닉네임입니다.
                duplicate user info:
                  value:
                    message: 중복된 유저 정보입니다.
                
  /users/refresh:
    post:
      tags:
        - users
      summary: 토큰 재발급
      description: 토큰 재발급입니다.
      requestBody:
        content:
          application/json:
            schema:
              properties:
                refresh_token:
                  type: string
                  example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm92aWRlciI6IkFQUExFIiwiZW1haWwiOiIwMDAzMTkuNDA0N2MzMGQ0MDQ2NDRmOTlmMTVmZWZiODQxYmIwOGIuMDIzOSIsImV4cCI6MTcxMDU2Mzg2NywiaWF0IjoxNjk1MDExODY3fQ.wfILCBkBOQQMHGFwRaguKkhfV50lyNREMUYq0CSxkLY
          required: true
      security:
        - leporemartTokenAuth: []
      responses:
        '200':
          description: 토큰 갱신 성공
          content:
            application/json:
              example:
                message: token refreshed successful
                data:
                  access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm92aWRlciI6IkFQUExFIiwiZW1haWwiOiIwMDAzMTkuYWIwYjk0NTNhMWE5NDgxNzhiOGQ4MWE5NzRjN2YwMTUuMTcyMiIsImV4cCI6MTY5MjAzOTA4NCwiaWF0IjoxNjkyMDI4Mjg0fQ.-Y5RtpVnB1zXQksA9fNKXYCB3D_qMfInXMTYbLp8NNE
                  refresh_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm92aWRlciI6IkFQUExFIiwiZW1haWwiOiIwMDAzMTkuYWIwYjk0NTNhMWE5NDgxNzhiOGQ4MWE5NzRjN2YwMTUuMTcyMiIsImV4cCI6MTcwNzU4MDI4NCwiaWF0IjoxNjkyMDI4Mjg0fQ.XWeYAH80bEMfwQCG9bQTrd-46zP5bACEKSw9cSBLRiU

        '400':
          description: refresh token 존재하지 않습니다.
          content:
            application/json:
              example:
                message: refresh_token을 보내주세요.
                code: JWT_400_NOT_FOUND_TOKEN

        '403':
          description: 잘못된 토큰입니다.
          content:
            application/json:
              example:
                message: 잘못된 토큰입니다.
                code: JWT_403_INVALID_ACCESSTOKEN
  /items:
    get:
      tags:
        - items
      summary: 전체 작품 조회
      description: 전체 작품을 조회합니다.
      parameters:
        - name: page_number
          in: query
          schema:
            type: integer
        - name: ordering
          in: query
          schema:
            type: string
        - name: category
          in: query
          schema:
            type: string
        - name: nickname
          in: query
          schema:
            type: string
          description: 판매자용 전체 작품 조회
        - name: search
          in: query
          schema:
            type: string
        - name: price
          in: query
          schema:
            type: integer
            format: int64
            minimum: 1000
            maximum: 1000000
      security:
        - leporemartTokenAuth: []
          description: access token 존재 유무에 따라 회원과 비회원 구분합니다.
      responses:
        '200':
          description: 전체 작품 조회 성공
          content:
            application/json:
              example:
                list: {
                    total_count: 1,
                    items: [
                        {
                            item_id: 1,
                            nickname: 하잉,
                            title: zzㅋㅋ123,
                            price: 2345,
                            thumbnail_image: "https://leporem-art-media-dev.s3.amazonaws.com/items/item_image/a54e4678-da0e-4098-aec9-40cd440be128.jpg",
                            like_count: 1,
                            avg_rating: null,
                            time_diff: "32 22:40:07.055202",
                            current_amount: 0,
                            is_liked: false
                        }
                    ]
                }
        '400':
          description: 전체 작품 조회 실패
          content:
            application/json:
              examples:
                PageNotAnInteger:
                  value:
                    message: PageNotAnInteger
                EmptyPage:
                  value:
                    message: EmptyPage
  /items/filter:
    get:
      tags:
        - items
      summary: 회원 전체 작품 조회
      description: 회원일 때, 전체 작품을 조회합니다.
      parameters:
        - name: page_number
          in: query
          schema:
            type: integer
        - name: ordering
          in: query
          schema:
            type: string
        - name: category
          in: query
          schema:
            type: string
        - name: nickname
          in: query
          schema:
            type: string
          description: 판매자용 전체 작품 조회
        - name: search
          in: query
          schema:
            type: string
        - name: price
          in: query
          schema:
            type: integer
            format: int64
            minimum: 1000
            maximum: 1000000
      security:
        - leporemartTokenAuth: []
      responses:
        '200':
          description: 전체 작품 조회 성공
          content:
            application/json:
              example:
                list: {
                  total_count: 1,
                  items: [
                    {
                      item_id: 1,
                      nickname: 하잉,
                      title: zzㅋㅋ123,
                      price: 2345,
                      thumbnail_image: "https://leporem-art-media-dev.s3.amazonaws.com/items/item_image/a54e4678-da0e-4098-aec9-40cd440be128.jpg",
                      like_count: 1,
                      avg_rating: null,
                      time_diff: "32 22:40:07.055202",
                      current_amount: 0,
                      is_liked: false
                    }
                  ]
                }
        '400':
          description: 전체 작품 조회 실패
          content:
            application/json:
              examples:
                PageNotAnInteger:
                  value:
                    message: PageNotAnInteger
                EmptyPage:
                  value:
                    message: EmptyPage
  /items/guest:
    get:
      tags:
        - items
      summary: 비회원 전체 작품 조회
      description: 비회원일 때, 전체 작품을 조회합니다.
      parameters:
        - name: page_number
          in: query
          schema:
            type: integer
        - name: ordering
          in: query
          schema:
            type: string
        - name: category
          in: query
          schema:
            type: string
        - name: nickname
          in: query
          schema:
            type: string
        - name: search
          in: query
          schema:
            type: string
        - name: price
          in: query
          schema:
            type: integer
            format: int64
            minimum: 1000
            maximum: 1000000
      responses:
        '200':
          description: 전체 작품 조회 성공
          content:
            application/json:
              example:
                list: {
                  total_count: 1,
                  items: [
                    {
                      item_id: 1,
                      nickname: 하잉,
                      title: zzㅋㅋ123,
                      price: 2345,
                      thumbnail_image: "https://leporem-art-media-dev.s3.amazonaws.com/items/item_image/a54e4678-da0e-4098-aec9-40cd440be128.jpg",
                      like_count: 1,
                      avg_rating: null,
                      time_diff: "32 22:40:07.055202",
                      current_amount: 0,
                      is_liked: false
                    }
                  ]
                }
        '400':
          description: 전체 작품 조회 실패
          content:
            application/json:
              examples:
                PageNotAnInteger:
                  value:
                    message: PageNotAnInteger
                EmptyPage:
                  value:
                    message: EmptyPage

  /notifications/register:
    post:
      tags:
        - notifications
      summary: 푸시 알림 기기 등록
      description: 푸시 알림 기기를 등록합니다.
      requestBody:
        content:
          application/json:
            schema:
              properties:
                device_token:
                  type: string
                  example: fyBSTdnGQ9CBZviM_X3M4o:APA91bFoROw8QK6Q5Twu6AFVHWgf1CSLPdJgiRbaJpCKd_YqcWI6s07WmrDZE_ZPdDUq0R_P8IvvqCWsuJ21rrqwkiZoifV7CZWSvwfykgxdeu3tw1QJP5buat9FpAFDDJfhQZ_3qs9u
        required: true
      security:
        - leporemartTokenAuth: []
      responses:
        '201':
          description: 푸시 알림 기기 등록 성공
          content:
            application/json:
              example:
                message: success
        '400':
          description: 푸시 알림 기기 등록 실패
          content:
            application/json:
              example:
                message: failed

  /notifications/specific:
    get:
      tags:
        - notifications
      summary: 싱글 유저 푸시 알림
      description: 싱글 유저에게 푸시 알림을 보냅니다.
      parameters:
        - name: token
          in: query
          schema:
            type: string
        - name: title
          in: query
          schema:
            type: string
        - name: body
          in: query
          schema:
            type: string
        - name: deep_link
          in: query
          schema:
            type: string
      security:
        - leporemartTokenAuth: []
      responses:
        '200':
          description: 싱글 유저 푸시 알림 성공
          content:
            application/json:
              example:
                message: success